### ISSUE TITLE
add Mining Overview Dashboard

### ISSUE THREAD

**Issue by Geraldidi** [rodneymo/rig-monitorv2#10]

**Comment by Geraldidi** [comment]
yes, let's say a dashboard that informs the general status of the mining operation, compact, simple but the most important information being shown 

if there are 2 pools, 3 coins being mined,2 mining software being used the dashboard should show the stats about the general status of the mining operation. 


Maybe something like this to know that is happening to rigs 
Rigs info:
Name    Status   current hashrate       GPUs  coin        pool     miner    online time GPU T° (Highest) Power Consumption
Rig 1    online    180                 6/8   eth      nanopool  claymore    10:10:01       65			8150W
Rig 2    online    179                 6/6   eth      ethermine claymore    13:10:01       59			830W
Rig 3    online    7500                4/4   xmr      nanopool  cast-xmr    203:10:01      53			760W

Rigs Info: online/offline, gpus online/gpus installed, current hashrate, pool working for, gpus temp, gpus fan, power consumption

And for some more detail these are some ideas about what could be, it's similar to dashboard mining overview from rig-monitorv1

-Profitability info: 
	total income daily/monthly of all coins mined
	income for each coin being mined
	awaiting payout/minimum payout for each coin
	electricity cost for this month

-Coins+Miner Info: for each coin: 	
	current hashrate/target

-Power info: 
	current power consumption vs target power consumption
	power consumption vs time

-Pools Info: for each pool: 
	current hashrate+average+ workers online vs time

This is just an idea of having a dashboard to see everything, maybe not as detailed but knowing if the operation is going well or bad

**Comment by rodneymo** [comment]
Thanks for the input. I'll make sure I'll cover this once I have some time.

**Comment by rodneymo** [comment]
Take a look at this one. I build it for some of my miners using xmr-stak. xmr-stak API does not provide the fan&temp KPIs, but that's easy enough to copy from some of the other templates.
Also the profitability panels are not included as the feature is not yet finished. 
I will include this example in future deliveries.
![final](https://user-images.githubusercontent.com/31135266/40699666-f797ac32-63d5-11e8-9264-9f12519b7175.jpg)
[Mining Overview Example Dashboard - 40-inch screen-1527655748993.json.zip](https://github.com/rodneymo/rig-monitorv2/files/2052440/Mining.Overview.Example.Dashboard.-.40-inch.screen-1527655748993.json.zip)

**Comment by rodneymo** [comment]
I am closing this for now. I'll add the profitability panels once they are finalized

**Comment by Geraldidi** [comment]
profitability will have how much electricity will cost for that month and how much profit will make so this is going great and can be closed because profitability is a feature in development  thanks
