### ISSUE TITLE
Add Equihash miners support

### ISSUE THREAD

**Issue by kropotkin5** [rodneymo/rig-monitorv2#17]
It would be great to have support of popular equihash algo miners:
- EWBF
- Bminer
- DTSM miner

**Comment by rodneymo** [comment]
Are you using these miners? Could you provide me the API output (hopefully json) and the URL used to query each miner?

**Comment by rodneymo** [comment]
Closed this one and created 3 new issues, one per miner:
https://github.com/rodneymo/rig-monitorv2/issues/28
https://github.com/rodneymo/rig-monitorv2/issues/29
https://github.com/rodneymo/rig-monitorv2/issues/30
