### ISSUE TITLE
Import to existing Grafana

### ISSUE THREAD

**Issue by DanielGrankvist** [rodneymo/rig-monitorv2#18]
Hi, is it possible to import to an existing Grafana?
I've already got a Dashbaord for other stuff in Grafana and would like thos on a new Dashboard.

`root@localhost:~$ sudo sqlite3 /var/lib/grafana/grafana.db
SQLite version 3.19.3 2017-06-08 14:26:16
Enter ".help" for usage hints.
sqlite> .separator ","
sqlite> .import /home/root/dashboard.csv dashboard
/home/root/dashboard.csv:1: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:2: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:3: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:4: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:5: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:6: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:7: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:8: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:9: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:10: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:11: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:12: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:13: INSERT failed: UNIQUE constraint failed: dashboard.id
/home/root/dashboard.csv:14: INSERT failed: UNIQUE constraint failed: dashboard.id
`

Thanks!

**Comment by rodneymo** [comment]
Try this.

1) Create a temp table similar to dashboard:
CREATE TABLE `temp` (
  `version` INTEGER NOT NULL
, `slug` TEXT NOT NULL
, `title` TEXT NOT NULL
, `data` TEXT NOT NULL
, `org_id` INTEGER NOT NULL
, `created` DATETIME NOT NULL
, `updated` DATETIME NOT NULL
, `updated_by` INTEGER NULL, `created_by` INTEGER NULL, `gnet_id` INTEGER NULL, `plugin_id` TEXT NULL, `folder_id` INTEGER NOT NULL DEFAULT 0, `is_folder` INTEGER NOT NULL DEFAULT 0, `has_acl` INTEGER NOT NULL DEFAULT 0, `uid` TEXT NULL);

2) read from temp table, except unique ID, and insert it into dashboard
insert into dashboard (version,slug,title,data,org_id,created,updated,updated_by,created_by,gnet_id,plugin_id,folder_id,is_folder,has_acl,uid )select version,slug,title,data,org_id,created,updated,updated_by,created_by,gnet_id,plugin_id,folder_id,is_folder,has_acl,uid from temp;

Let me know if that works for you

**Comment by rodneymo** [comment]
Closing this for now. Let me know if you still have problems.
