### ISSUE TITLE
Add password parameter for rig

### ISSUE THREAD

**Issue by sbervinov** [rodneymo/rig-monitorv2#22]
Hi. I cannot see password parameter for rig. W\o that your program is not usable for me. Can you add it?

I`m talking about rig configuration:

#RIG_ID, MINER, PRIMARY_POOL_LABEL, SECONDARY_POOL_LABEL, RIG_URL/IP, INSTALLED_GPUS/THREADS,TARGET_HASHRATE,TARGET_HASHRATE_2nd_COIN,PLUG_TYPE,PLUG_IP,MAX_POWER,MAX_TEMP

You have RIG_URL/IP, but you do not have RIG_PASSWORD

**Comment by rodneymo** [comment]
Currently the claymore implementation uses the http remote mgmt, not the json-rpc, as the html output has more info than the json. How do you pass the password as part of the http request? I couldn't find info about it anywhere

**Comment by sbervinov** [comment]
I use Phoenix Miner, but it and Claymore work the same as I know.
In Phoenix Miner I use -cdmport -cdmpass. In Claymore I used -mport -mpsw. W\o password it is not secure. Sometime I can see in logs requests to restart miner, but because miner is protected by password, restart commands ignored.

**Comment by rodneymo** [comment]
> Using HTTP request to IP:port I can see text logs only. For that I do not need password.

That's fine for rig-monitor. Then why would I need to implement the password support if it can already read the stats without password?

**Comment by StefanOberhumer** [comment]
Just as info if you need using the RPC API on Claymore:
The Claymore RPC API supports the parameter "psw" to pass a password - eg:
echo "{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"miner_getstat1\",\"psw\":\"SECRET_PASSWORD\"}" | netcat <RIG_IP> <PORT>

**Comment by rodneymo** [comment]
Thanks @StefanOberhumer  but the claymore implementation uses html as it provides better data granularity e.g. gnu shares
My understanding is that even if the password is set you can still query the stats via http w/o password, is that not the case?

**Comment by StefanOberhumer** [comment]
I think you are right - ```even if the password is set you can still query the stats via http w/o password```
So if you query claymore using http, you should not need any password (think i've tried claymore 11.6 with that)
Btw: The html result of the http request in claymore also includes the info of the RPC API miner_getstat1 call!

**Comment by StefanOberhumer** [comment]
> ... e.g. gnu shares

What are "gnu" shares ?

**Comment by rodneymo** [comment]
gpu shares, nothing to do with animals or sw licensing ;-)

**Comment by rodneymo** [comment]
Closing this issues as it seems it does not affect the html end point
