### ISSUE TITLE
Allow executing a custom script on low hash rate alert triggers

### ISSUE THREAD

**Issue by tcsekhar** [rodneymo/rig-monitorv2#23]
I have few Avocent Power Distribution Units which has a serial interface to send switch off/restart signal. It will be nice if you could allow calling a shell script or custom Go Lang module when alert trigger executes.

**Comment by rodneymo** [comment]
Sounds like a good idea. Don't you need to pass an identifier to your script in order to reset the right, rig?
I suggets to pass both rig name and IP for flexibility.

**Comment by rodneymo** [comment]
Check version 2.2.d8. Feature will be included in final 2.2 version
