### ISSUE TITLE
Support of upcoming ethminer-0.15 ?

### ISSUE THREAD

**Issue by StefanOberhumer** [rodneymo/rig-monitorv2#26]
As the upcoming ethminer-0.15 (https://github.com/ethereum-mining/ethminer) has also an integrated http server it would be nice if you could support that.

Btw: Cool project :+1 - I hope you'll release the sourcecode!

**Comment by rodneymo** [comment]
Hi Stefan,

do you have an example of the API and output? I am away from my test environment for the coming week so I won't be able to install it and test it a real rig.

**Comment by StefanOberhumer** [comment]
As my PR1195 (https://github.com/ethereum-mining/ethminer/pull/1195) was merged:
* API call "miner_getstat1" should match claymore output
* Changed unit in html form mh/s to MH/s

I adapted the information in this issue

**Comment by rodneymo** [comment]
Thanks. I'll schedule support for this soon.

**Comment by rodneymo** [comment]
@StefanOberhumer, I am going to start working on this now. Do you have a json example? I know you told me it should be similar to claymore's json-rpc, but I'd like to have a real example of the output

**Comment by StefanOberhumer** [comment]
`echo "{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"miner_getstat1\"}" | netcat RIG_IP RIG_PORT > rpcresult.txt`

results in: [rpcresult.txt](https://github.com/rodneymo/rig-monitorv2/files/2074642/rpcresult.txt)

**Be aware:**
* http and rpc-api use **different ports** in ethminer!
* The connection is not closed from the server after answering the rpc  (you have to close the socket by yourself) -  I think claymore closes the connection from server side.

If you want also support ethminer-0.14 following differences are between ethminer-0.14 <-> ethminer-0.15.0.dev11-96+commit.6b02ef2f:

* in 0.14 there were spaces in `Temperature and Fan speed(%) pairs for all GPUs.` between each GPU
* in 0.14 there was no http server (just RPC API available)

**Comment by rodneymo** [comment]
Ok. I have added support for ethminer 0.15 in version 2.3.d.3 (developement). This will be included in final version 2.3.
Thanks you for highlighting the diffs between 0.14 and 0.15. 
1) my implementation uses the json-rpc  interface
2) when you say there were spaces between temp & fan pairs, do you mean like this?
        "54;30 62;30 62;58 62;60 62;61 62;60 62;48 60;30",
or spaces between every metric like this?
        "54 30 62 30 62 58 62 60 62 61 62 60 62 48 60 30",

**Comment by StefanOberhumer** [comment]
> when you say there were spaces between temp & fan pairs, do you mean like this?
> "54;30 62;30 62;58 62;60 62;61 62;60 62;48 60;30",
> or spaces between every metric like this?
> "54 30 62 30 62 58 62 60 62 61 62 60 62 48 60 30",

None of them: it looked like
``` "54;30; 62;30; 62;58; 62;60; 62;61; 62;60; 62;48; 60;30", ```
I tested some other tools and some had problems parsing ```" 62"``` so I added a patch which removed the spaces

**Comment by rodneymo** [comment]
Ah. Easy one. Version 2.3.d.4 trims spaces before converting the fan, temp to ints

**Comment by StefanOberhumer** [comment]
> Ah. Easy one. Version 2.3.d.4 trims spaces before converting the fan, temp to ints

Yes - as there is currently no github - sourcecode I can not create a pull request ;-)

**Comment by StefanOberhumer** [comment]
Btw: Would helpful to add a link to the current downloadpage ( https://github.com/rodneymo/rig-monitorv2/releases ) into  README.md

**Comment by rodneymo** [comment]
Thanks for the tip. I'll close it when I publish the final 2.3 version.

**Comment by rodneymo** [comment]
Support added in version 2.3.0

**Comment by rodneymo** [comment]
@StefanOberhumer, I believe the hashrates reported in the the json-rpc response are in KH/s. Could you confirm?

**Comment by StefanOberhumer** [comment]
Yes - it is in kH/s
see: https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md#miner_getstat1
```
...
    "87221;54;0",                           // ETH hashrate in KH/s, submitted shares, rejected shares
    "14683;14508;14508;14508;14508;14508",  // Detailed ETH hashrate in KH/s per GPU
...
```
