### ISSUE TITLE
Support for Suprnova pools

### ISSUE THREAD

**Issue by rodneymo** [rodneymo/rig-monitorv2#33]
Added in version 2.3.d.2

**Comment by kropotkin5** [comment]
Please add balance infos for suprnova with this api call >> getuserbalance

**Comment by rodneymo** [comment]
@kropotkin5, rig-monitor 2.3.d.6 (development) adds support for suprnova getuserbalance to the MPOS module. Please let me know if it works for you.

**Comment by rodneymo** [comment]
Support added in version 2.3.0
