### ISSUE TITLE
Add Unimining (YiiMP) pool support

### ISSUE THREAD

**Issue by eX74** [rodneymo/rig-monitorv2#39]
Another famous pool engine : YiiMP

Here is the API doc : 

https://www.unimining.net/site/api

**Comment by rodneymo** [comment]
Plus the standard API: [http://yiimp.eu/site/api](url)

**Comment by rodneymo** [comment]
@eX74, can you send me a real example of the wallet API results for Unimining? I need it to construct the json decoding accurately and often API examples have some subtle differences from real implementations

**Comment by eX74** [comment]
Well, here it is :

http://pickaxe.pro/api/wallet?address=WALLET_ADDRESS :  

{"currency": "RVN", "unsold": 24.915895704089802, "balance": 0.00000000, "unpaid": 24.91589570, "paid24h": 84.74608473, "total": 109.66198043}

 http://pickaxe.pro/api/walletEx?address=WALLET_ADDRESS : 

{"currency": "RVN", "unsold": 24.915895704089802, "balance": 0.00000000, "unpaid": 24.91589570, "paid24h": 84.74608473, "total": 109.66198043, "miners": [{"version": "ccminer\/2.2.6", "password": "c=RVN", "ID": "", "algo": "x16r", "difficulty": 36, "subscribe": 1, "accepted": 18554258.719, "rejected": 2319282.34}, {"version": "ccminer\/2.2.6", "password": "c=RVN", "ID": "", "algo": "x16r", "difficulty": 38, "subscribe": 1, "accepted": 34817897.533, "rejected": 0}]}

This note may be usefull : 
The api server limits are set to 10 queries/mn by IP and method, abuse on API calls frequency affects the pool network efficiency and may temporary or permanently ban your IP from the api service.

The API is the same for unimining.net, Yiimp. Didn't find a way to have the current hashrate for miners.

**Comment by rodneymo** [comment]
I have a dev implementation of the yiimp API (also with support for the extended unimining API). Care to test it?

**Comment by rodneymo** [comment]
Support added in release 3.2

**Comment by eX74** [comment]
Hi,

Nice work, will try this next week on my test machines.

Really sad that I can't use it on my production environment.

Will also take a look at Nicehash.

Regards,

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
