### ISSUE TITLE
Influxdb error on fairpool

### ISSUE THREAD

**Issue by eX74** [rodneymo/rig-monitorv2#41]
I'm facing again the influxdb error, the trace is pointing to fairpool : 

ERROR: 2018/06/14 06:34:22 influxdb.go:39: DBDaemon could not write record batch to influxDB...
TRACE: 2018/06/14 06:34:22 influxdb.go:41: Failed with error: {"error":"partial write: unable to parse 'worker_stats,label=label_fairpool,pool_type=FAIRPOOL,rig_id=drake hr= 1528950776': missing field value dropped=0"}

**Comment by rodneymo** [comment]
This seems like a different error. Could you attach a complete trace only with fair pool enabled?

You need the following flags: ./grm -t -r -1 -m -1 -p <fairpool>

<fairpool> is the index line of fairpool in the config file starting from 1

**Comment by eX74** [comment]
TRACE: 2018/06/14 07:08:21 main.go:124: List of rigs: []miner.RigConfig{}
TRACE: 2018/06/14 07:08:21 main.go:125: List of pools: []pool.PoolConfig{pool.PoolConfig{Label:"label_fairpool", Type:"FAIRPOOL", Crypto:"loki", URL:"https://loki.fairpool.xyz", Token:"", Wallet:"WALLET_ADDRESS.PAYMENTID"}}
INFO: 2018/06/14 07:08:21 influxdb.go:26: Starting DBDaemon routine...
INFO: 2018/06/14 07:08:21 influxdb.go:94: Creating influxDB connection to http://localhost:8086 ...
INFO: 2018/06/14 07:08:22 main.go:142: Launching pool monitor worker: 0
INFO: 2018/06/14 07:08:22 main.go:142: Launching pool monitor worker: 1
INFO: 2018/06/14 07:08:22 influxdb.go:94: Creating influxDB connection to http://localhost:8086 ...
INFO: 2018/06/14 07:08:22 influxdb.go:94: Creating influxDB connection to http://localhost:8086 ...
INFO: 2018/06/14 07:08:22 main.go:142: Launching pool monitor worker: 2
INFO: 2018/06/14 07:08:22 influxdb.go:94: Creating influxDB connection to http://localhost:8086 ...
INFO: 2018/06/14 07:08:22 pool-monitor.go:52: New pool monitor job received: label_fairpool
TRACE: 2018/06/14 07:08:22 pool-monitor.go:54: New pool monitor job received: &pool.PoolConfig{Label:"label_fairpool", Type:"FAIRPOOL", Crypto:"loki", URL:"https://loki.fairpool.xyz", Token:"", Wallet:"WALLET_ADDRESS.PAYMENTID"}
INFO: 2018/06/14 07:08:22 fairpool.go:36: Querying FAIRPOOL minerStats.
TRACE: 2018/06/14 07:08:22 fairpool.go:38: Pool query: https://loki.fairpool.xyz/api/stats?login=WALLET_ADDRESS.PAYMENTID
TRACE: 2018/06/14 07:08:24 pool-monitor.go:39: Response from https://loki.fairpool.xyz/api/stats?login=WALLET_ADDRESS.PAYMENTID: {
   "unconfirmed": 1786148184,
   "invalid": false,
   "threshold": 15000000000,
   "workers": [
      [
         "RIG0",
         null
      ],
      [
         "RIG1",
         2006.7663655110377
      ],
      [
         "RIG2",
         5303.326540000138
      ],
      [
         "RIG3",
         6623.1347791437065
      ]
   ],
   "balance": 13528758771,
   "method": "stats",
   "paid": 282337968136,
   "blocksTillNextConfirmation": 5
}
INFO: 2018/06/14 07:08:24 fairpool.go:44: minerStats query succeeded!
INFO: 2018/06/14 07:08:24 fairpool.go:49: Querying FAIRPOOL networkStats.
TRACE: 2018/06/14 07:08:24 fairpool.go:51: Pool query: https://loki.fairpool.xyz/api/network
TRACE: 2018/06/14 07:08:24 pool-monitor.go:39: Response from https://loki.fairpool.xyz/api/network: {
   "blockchainHeight": 30655,
   "reward": 113256812035,
   "method": "network",
   "networkHashrate": 27500254.50294861,
   "currentDifficulty": 3285113710
}
INFO: 2018/06/14 07:08:24 fairpool.go:57: networkStats query succeeded!
TRACE: 2018/06/14 07:08:24 fairpool.go:88: Write point to DB:
TRACE: 2018/06/14 07:08:24 fairpool.go:89: 	Measurement: pool_stats
TRACE: 2018/06/14 07:08:24 fairpool.go:90: 	Tags: map[pool_type:FAIRPOOL label:label_fairpool]
TRACE: 2018/06/14 07:08:24 fairpool.go:91: 	Fields: map[paid:1.3528758771e+10 balance:1.3528758771e+10 unconfirmed_balance:1.786148184e+09 hr:13933.227684654881 active_workers:4]
TRACE: 2018/06/14 07:08:24 fairpool.go:119: Write point to DB:
TRACE: 2018/06/14 07:08:24 fairpool.go:120: 	Measurement: worker_stats
TRACE: 2018/06/14 07:08:24 fairpool.go:121: 	Tags: map[pool_type:FAIRPOOL label:label_fairpool rig_id:RIG0]
TRACE: 2018/06/14 07:08:24 fairpool.go:122: 	Fields: map[hr:<nil>]
TRACE: 2018/06/14 07:08:24 fairpool.go:119: Write point to DB:
TRACE: 2018/06/14 07:08:24 fairpool.go:120: 	Measurement: worker_stats
TRACE: 2018/06/14 07:08:24 influxdb.go:54: New record received by DBDaemon: pool_stats map[pool_type:FAIRPOOL label:label_fairpool] map[active_workers:4 balance:1.3528758771e+10 hr:13933.227684654881 paid:1.3528758771e+10 unconfirmed_balance:1.786148184e+09] <nil> 2018-06-14 07:08:24.081532829 +0200 CEST m=+2.791592853
TRACE: 2018/06/14 07:08:24 fairpool.go:121: 	Tags: map[pool_type:FAIRPOOL label:label_fairpool rig_id:RIG1]
TRACE: 2018/06/14 07:08:24 influxdb.go:54: New record received by DBDaemon: worker_stats map[label:label_fairpool pool_type:FAIRPOOL rig_id:RIG0] map[] <nil> 2018-06-14 07:08:24.082248141 +0200 CEST m=+2.792308270
TRACE: 2018/06/14 07:08:24 fairpool.go:122: 	Fields: map[hr:2006.7663655110377]
TRACE: 2018/06/14 07:08:24 fairpool.go:119: Write point to DB:
TRACE: 2018/06/14 07:08:24 fairpool.go:120: 	Measurement: worker_stats
TRACE: 2018/06/14 07:08:24 fairpool.go:121: 	Tags: map[pool_type:FAIRPOOL label:label_fairpool rig_id:RIG2]
TRACE: 2018/06/14 07:08:24 fairpool.go:122: 	Fields: map[hr:5303.326540000138]
TRACE: 2018/06/14 07:08:24 fairpool.go:119: Write point to DB:
TRACE: 2018/06/14 07:08:24 fairpool.go:120: 	Measurement: worker_stats
TRACE: 2018/06/14 07:08:24 fairpool.go:121: 	Tags: map[rig_id:RIG3 pool_type:FAIRPOOL label:label_fairpool]
TRACE: 2018/06/14 07:08:24 fairpool.go:122: 	Fields: map[hr:6623.1347791437065]
TRACE: 2018/06/14 07:08:24 influxdb.go:54: New record received by DBDaemon: worker_stats map[rig_id:RIG1 label:label_fairpool pool_type:FAIRPOOL] map[hr:2006.7663655110377] <nil> 2018-06-14 07:08:24.083448349 +0200 CEST m=+2.793508374
TRACE: 2018/06/14 07:08:24 fairpool.go:149: Write point to DB:
TRACE: 2018/06/14 07:08:24 fairpool.go:150: 	Measurement: network_stats
TRACE: 2018/06/14 07:08:24 fairpool.go:151: 	Tags: map[pool_type:FAIRPOOL label:label_fairpool]
TRACE: 2018/06/14 07:08:24 fairpool.go:152: 	Fields: map[difficulty:3285113710 reward:113256812035 network_hr:2.750025450294861e+07]
TRACE: 2018/06/14 07:08:24 influxdb.go:54: New record received by DBDaemon: worker_stats map[label:label_fairpool pool_type:FAIRPOOL rig_id:RIG2] map[hr:5303.326540000138] <nil> 2018-06-14 07:08:24.083952255 +0200 CEST m=+2.794012280
TRACE: 2018/06/14 07:08:24 influxdb.go:54: New record received by DBDaemon: worker_stats map[label:label_fairpool pool_type:FAIRPOOL rig_id:RIG3] map[hr:6623.1347791437065] <nil> 2018-06-14 07:08:24.084395536 +0200 CEST m=+2.794455561
TRACE: 2018/06/14 07:08:24 influxdb.go:54: New record received by DBDaemon: network_stats map[label:label_fairpool pool_type:FAIRPOOL] map[difficulty:3285113710 network_hr:2.750025450294861e+07 reward:113256812035] <nil> 2018-06-14 07:08:24.084928453 +0200 CEST m=+2.794988477
TRACE: 2018/06/14 07:08:42 functions.go:139: Alloc = 3 MiB	TotalAlloc = 17 MiB	Sys = 27 MiB	NumGC = 6
TRACE: 2018/06/14 07:08:42 functions.go:147: Number of Go routines running: 9
TRACE: 2018/06/14 07:08:42 main.go:229: Number of items in rigJobQueue: 0
TRACE: 2018/06/14 07:08:42 main.go:230: Number of items in powerJobQueue: 0
TRACE: 2018/06/14 07:08:42 main.go:231: Number of items in poolJobQueue: 0
TRACE: 2018/06/14 07:08:42 main.go:232: Number of items in marketJobQueue: 1
TRACE: 2018/06/14 07:08:42 main.go:233: Number of items in rulesManagerJobQueue: 0
TRACE: 2018/06/14 07:08:42 main.go:234: Number of items in recordQueue(DB): 0
ERROR: 2018/06/14 07:08:51 influxdb.go:39: DBDaemon could not write record batch to influxDB...
TRACE: 2018/06/14 07:08:51 influxdb.go:41: Failed with error: {"error":"partial write: unable to parse 'worker_stats,label=label_fairpool,pool_type=FAIRPOOL,rig_id=RIG0 hr= 1528952904': missing field value dropped=0"}
TRACE: 2018/06/14 07:09:02 functions.go:139: Alloc = 3 MiB	TotalAlloc = 17 MiB	Sys = 27 MiB	NumGC = 6
TRACE: 2018/06/14 07:09:02 functions.go:147: Number of Go routines running: 11

**Comment by rodneymo** [comment]
Should be fixed now.
[grm-2.3.0_hf41-linux-arm7.tar.gz](https://github.com/rodneymo/rig-monitorv2/files/2101467/grm-2.3.0_hf41-linux-arm7.tar.gz)

**Comment by eX74** [comment]
Nice work, stable since an hour, no more errors.
