### ISSUE TITLE
improve power mgmt usage documentation

### ISSUE THREAD

**Issue by rodneymo** [rodneymo/rig-monitorv2#42]

**Comment by rodneymo** [comment]
@tcsekhar, I have moved this issue to the right project

**Comment by tcsekhar** [comment]
May I know where the right project is please?

**Comment by rodneymo** [comment]
This is the right project. Currently the code has not been open sourced. 
In the meantime, if you want to use a custom script with power mgmt you'd just replace the smartplug type with the path of the custom script in the respective rig entries e.g.

`"rig10,ethminer,label_hashvault,,//127.0.0.1:12001,8,1500,,external/myscript.sh,,1000,75",`
and configure the applicable power rules in the power mgmt section

**Comment by tcsekhar** [comment]
I tried. But its not calling the batch script. Can you please let me know what I am doing wrong?

Here is the log from RigMonitor:
INFO: 2018/06/16 10:28:42 power-rules-manager.go:46: Record count for hr below defined threshold (420). Resetting miner07 rig via EXTERNAL/RESTARTMINER.BAT()

Here is the config.toml configuration:
rigList = [
"miner01,claymore,label_ethermine,,http://10.0.1.137:3333,13,390,0,external/restartminer.bat,,1800,85"
]

PowerMgmtRules=[
"miner01,true,hr,miner_system,420,120,false,,,,"
]

Here is the batch file in the external directory restartminer.bat:
echo "%date%%time%: Rigmonitor called to restart %1" >> restart_log.txt 2>&1
IF "%1"=="miner01" (
    echo "Restarting miner01" >> restart_log.txt 2>&1
  )

**Comment by rodneymo** [comment]
I’ll try it in a couple of hours

**Comment by rodneymo** [comment]
@tcsekhar, a couple of things to try:

1) try putting the external script in the same dir as grm
2) if the above works then try replacing the forward slash with a back slash i.e. external\restartminer.bat  
3) try using the absolute path for script e.g. c:\xxxx\xxx\..\ restartminer.bat

**Comment by tcsekhar** [comment]
I tried all 3 - nothing worked. 

Placed the bat file in the directory where grm-.exe resides - didn't work
Change the fwd slash to back slash - it didn't work
Used the absolute path, still didn't work

INFO: 2018/06/17 11:07:38 power-rules-manager.go:46: Record count for hr below defined threshold (420). Resetting miner01 rig via C:\DATA\RESTARTMINER.BAT()
INFO: 2018/06/17 11:09:38 power-rules-manager.go:46: Record count for hr below defined threshold (420). Resetting miner01 rig via C:/DATA/RESTARTMINER.BAT()
INFO: 2018/06/17 11:11:38 power-rules-manager.go:46: Record count for hr below defined threshold (420). Resetting miner01 rig via RESTARTMINER.BAT()
INFO: 2018/06/17 11:13:38 power-rules-manager.go:46: Record count for hr below defined threshold (420). Resetting miner01 rig via EXTERNAL/RESTARTMINER.BAT()
INFO: 2018/06/17 11:15:38 power-rules-manager.go:46: Record count for hr below defined threshold (420). Resetting miner01 rig via EXTERNAL\RESTARTMINER.BAT()

**Comment by rodneymo** [comment]
Alright, I will setup a windows env tonight and test it

**Comment by tcsekhar** [comment]
Also, if the RESTART was called once, it shouldn't call it again for the same rig for at-least 5 minutes correct? I see that its been called every minute it runs.

**Comment by rodneymo** [comment]
> Also, if the RESTART was called once, it shouldn't call it again for the same rig for at-least 5 minutes correct? I see that its been called every minute it runs.

That's correct.

It seems there's an error in your config file. It should be something like this:
`"miner01,claymore,label_ethermine,,http://10.0.1.137:3333,13,390,,script,external\restartminer.bat,1800,85"`

Let me know if that works for you

**Comment by tcsekhar** [comment]
That was it. I included the Script parameter and it works like a charm. It calls the script only after 5 minutes of last firing. I tried with different folders and full path, all combinations do work.

All good!!

**Comment by rodneymo** [comment]
Instructions add to advanced configuration page, which is part of the installation instrusctions.
