### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by bryankanderson** [rodneymo/rig-monitorv2#46]
Using GRM 2.3.0 on MacOSX 10.9.  Issue occurs after running many hours (12-24) and just started a few days ago.  Log with Trace enabled:

INFO: 2018/06/20 23:59:24 nanopool.go:183: minerPayments query succeeded!
TRACE: 2018/06/20 23:59:24 nanopool.go:212: Write point to DB:
TRACE: 2018/06/20 23:59:24 nanopool.go:213: 	Measurement: pool_stats
TRACE: 2018/06/20 23:59:24 nanopool.go:214: 	Tags: map[label:label_nanopool_eth pool_type:NANOPOOL]
TRACE: 2018/06/20 23:59:24 nanopool.go:215: 	Fields: map[hr_avg_3h:185.1 hr_avg_6h:192.2 active_workers:1 balance:0.04842168 hr_avg_1h:206.8 hr_avg_24h:198 hr:255 unconfirmed_balance:0 hr_avg_12h:198.8]
TRACE: 2018/06/20 23:59:24 functions.go:59: Last record for SELECT last(shares) from pool_shares where label='label_nanopool_eth': 1529556000
TRACE: 2018/06/20 23:59:24 nanopool.go:242: Write point to DB:
TRACE: 2018/06/20 23:59:24 nanopool.go:243: 	Measurement: pool_shares
TRACE: 2018/06/20 23:59:24 nanopool.go:244: 	Tags: map[pool_type:NANOPOOL label:label_nanopool_eth]
TRACE: 2018/06/20 23:59:24 nanopool.go:245: 	Fields: map[shares:24]
TRACE: 2018/06/20 23:59:24 nanopool.go:282: Write point to DB:
TRACE: 2018/06/20 23:59:24 nanopool.go:283: 	Measurement: worker_stats
TRACE: 2018/06/20 23:59:24 nanopool.go:284: 	Tags: map[pool_type:NANOPOOL label:label_nanopool_eth rig_id:6xGTX1070]
TRACE: 2018/06/20 23:59:24 nanopool.go:285: 	Fields: map[avg_hr_24h:198 hr:255 avg_hr_1h:206.8 avg_hr_3h:185.1 avg_hr_6h:192.2 avg_hr_12h:198.8]
TRACE: 2018/06/20 23:59:24 functions.go:59: Last record for SELECT last(amount) from pool_payments where label='label_nanopool_eth': 1529257476
panic: runtime error: index out of range

goroutine 51 [running]:
go-rig-monitor/pool.(*PoolConfig).LoadNanopoolData(0xc42011ecc0, 0x1559640, 0xc42011ee40, 0xc42007df80)
	/Users/ramf/go/src/go-rig-monitor/pool/nanopool.go:339 +0x3794
go-rig-monitor/pool.Monitor(0xc420020500, 0x15, 0xc420022eb0, 0x7, 0xc420022f50, 0x7, 0xc420022ff0, 0x7, 0x1e, 0x3e8, ...)
	/Users/ramf/go/src/go-rig-monitor/pool/pool-monitor.go:61 +0x1a5
created by main.main
	/Users/ramf/go/src/go-rig-monitor/main.go:143 +0xb50

**Comment by rodneymo** [comment]
Do yo have the entire trace? I need to look into the response for the nano pool API? Alternatively you can send me you pool config line so I can try to reproduce it myself. For the latter, don't post it here., but send it to me via telegram PM.

**Comment by bryankanderson** [comment]
Here is the last minute or so, the trace from the whole day is about 4GB.

[grm_panic_trace.txt](https://github.com/rodneymo/rig-monitorv2/files/2124731/grm_panic_trace.txt)

**Comment by rodneymo** [comment]
Thanks. It seems the crash might be related to the network stats response:
TRACE: 2018/06/20 23:59:24 pool-monitor.go:39: Response from https://api.nanopool.org/v1/eth/blocks/0/1: {
   "status": false,
   "data": null
}
 I am going to try to replicate via a simulator.

But I found another, more critical issue with the SRBMiner so I created a new issue: [https://github.com/rodneymo/rig-monitorv2/issues/47](url)

**Comment by rodneymo** [comment]
I have created a hotfix for both #46 and #47 issues. you can get it here: [https://github.com/rodneymo/rig-monitorv2/releases/tag/2.3.1_hf_46_47](url)

**Comment by rodneymo** [comment]
Fixed in release 2.3.2
