### ISSUE TITLE
SRBMiner ERROR is preventing record insertion in InfluxDB

### ISSUE THREAD

**Issue by rodneymo** [rodneymo/rig-monitorv2#47]
@bryankanderson, could you attach full output of this particular rig? You can do that by querying the management port directly.

ERROR: 2018/06/20 23:59:22 influxdb.go:60: DBDaemon could not write record batch to influxDB...
TRACE: 2018/06/20 23:59:22 influxdb.go:62: Failed with error: {"error":"partial write: unable to parse 'miner_gpu,gpu_bus_id='

**Comment by bryankanderson** [comment]
Here is the JSON output, let me know if you need anything else:
`{
    "rig_name": "6xRX570",
    "cryptonight_type": "normalv7",
    "mining_time": 314536,
    "total_devices": 6,
    "total_threads": 12,
    "hashrate_total_now": 5539,
    "hashrate_total_1min": 5538,
    "hashrate_total_5min": 5538,
    "hashrate_total_30min": 5538,
    "hashrate_total_max": 6211,
    "pool": {
        "pool": "cryptonightv7.usa.nicehash.com:3363",
        "difficulty": 200007,
        "time_connected": "2018-06-18 17:36:59",
        "uptime": 314538,
        "latency": 117,
        "last_job_received": 1
    },
    "shares": {
        "total": 6319,
        "accepted": 6317,
        "rejected": 2,
        "avg_find_time": 49
    },
    "devices": [
        {
            "device": "GPU0",
            "device_id": 0,
            "model": "Radeon RX 570 Series",
            "bus_id": 6,
            "kernel_id": 1,
            "hashrate": 898,
            "core_clock": 1150,
            "memory_clock": 2020,
            "temperature": 56,
            "fan_speed_rpm": 3487
        },
        {
            "device": "GPU1",
            "device_id": 1,
            "model": "Radeon RX 570 Series",
            "bus_id": 8,
            "kernel_id": 1,
            "hashrate": 898,
            "core_clock": 1150,
            "memory_clock": 2020,
            "temperature": 55,
            "fan_speed_rpm": 2576
        },
        {
            "device": "GPU2",
            "device_id": 2,
            "model": "Radeon RX 570 Series",
            "bus_id": 13,
            "kernel_id": 1,
            "hashrate": 898,
            "core_clock": 1150,
            "memory_clock": 2020,
            "temperature": 54,
            "fan_speed_rpm": 2576
        },
        {
            "device": "GPU3",
            "device_id": 3,
            "model": "Radeon RX 570 Series",
            "bus_id": 10,
            "kernel_id": 1,
            "hashrate": 948,
            "core_clock": 1150,
            "memory_clock": 2020,
            "temperature": 56,
            "fan_speed_rpm": 2155
        },
        {
            "device": "GPU4",
            "device_id": 4,
            "model": "Radeon RX 570 Series",
            "bus_id": 12,
            "kernel_id": 1,
            "hashrate": 948,
            "core_clock": 1150,
            "memory_clock": 2020,
            "temperature": 50,
            "fan_speed_rpm": 1241
        },
        {
            "device": "GPU5",
            "device_id": 5,
            "model": "Radeon RX 570 Series",
            "bus_id": 11,
            "kernel_id": 1,
            "hashrate": 949,
            "core_clock": 1150,
            "memory_clock": 2020,
            "temperature": 54,
            "fan_speed_rpm": 1737
        }
    ]
}`

**Comment by rodneymo** [comment]
Thanks. I am away till Tuesday. I’ll fix it once I’m back

**Comment by rodneymo** [comment]
I have created a hotfix for both #46 and #47 issues. you can get it here: [https://github.com/rodneymo/rig-monitorv2/releases/tag/2.3.1_hf_46_47](url)

**Comment by rodneymo** [comment]
Fixed in release 2.3.2
