### ISSUE TITLE
Add Ethpool support

### ISSUE THREAD

**Issue by f00ch0w** [rodneymo/rig-monitorv2#48]
Here's the API: https://ethpool.org/api/pool

Thanks a lot!

**Comment by rodneymo** [comment]
Have you tried using the "ethermine" pool? The API is the same so it should work by simply replacing the ethermine URL with the ethpool URL e.g.

> "label_ethpool,ethermine,eth,https://api.ethpool.org,,wallet_address" 

Bear in mind that the config above is only for 2.x. If you are using the 3.x development then you need to add the pool correction factor (see config file for more info)

**Comment by rodneymo** [comment]
Tested and it's working. Instructions added to config file
