### ISSUE TITLE
Would be nice starting some charts with 0

### ISSUE THREAD

**Issue by StefanOberhumer** [rodneymo/rig-monitorv2#52]
I think setting in the following graphs "Axis / Y-Min" to 0 would give a better view
* 24h Profitability Forecast ($currency)
* 7d Profitability Forecast ($currency)
* 30d Profitability Forecast ($currency)

**Comment by rodneymo** [comment]
I understand and agree, but how would you show negative profitability i.e. costs are higher than revenue? Using 2nd (right) axis?

**Comment by StefanOberhumer** [comment]
Hmmm - you're right (havent't thought of that ;-) )
Give me a little time to try/play with that topic!
Please keep this issue open.....

**Comment by StefanOberhumer** [comment]
You were right - starting at 0 would hide displaying negative profitability.
So I think users have to adjust it by themselves.
