### ISSUE TITLE
Chart "INVALID SHARES REPORTED BY RIG" should start at 0

### ISSUE THREAD

**Issue by StefanOberhumer** [rodneymo/rig-monitorv2#54]
As I think the value can not become negative ;-) this chart should start at 0

If you have no invalid shares the Y-Range (auto)  is -1 to +1 which makes no sense!

**Comment by rodneymo** [comment]
Fixed in attached dashboard json 
[Mining Overview Dashboard 3.0-1530688886167.json.zip](https://github.com/rodneymo/rig-monitorv2/files/2162205/Mining.Overview.Dashboard.3.0-1530688886167.json.zip)
export
