### ISSUE TITLE
add support for PhoenixMiner

### ISSUE THREAD

**Issue by rodneymo** [rodneymo/rig-monitorv2#8]

**Comment by iLLNESS** [comment]
HTML output for PhoenixMiner https://pastebin.com/rcZfsZLm. PhoenixMiner also uses the same JSONRPC commands as Claymore (covered in EthMons API document bundled with Claymore) if you end up migrating in that direction.

**Comment by rodneymo** [comment]
implemented on 2.1.d.7. I will include this in the next official 2.1 release
