### ISSUE TITLE
support for XMR-proxy

### ISSUE THREAD

**Issue by rodneymo** [rodneymo/rig-monitorv2#9]
API details here: https://github.com/xmrig/xmrig-proxy/wiki/API

**Comment by syncro2017** [comment]
Hi There,
Here are the JSON from xmrig-proxy im running:

GET / endpoint
`{
    "id": "7497c4c417f304df",
    "worker_id": "proxy",
    "version": "2.6.0",
    "kind": "proxy",
    "mode": "simple",
    "ua": "xmrig-proxy/2.6.0 (Linux x86_64) libuv/1.8.0 gcc/5.4.0",
    "uptime": 169885,
    "donate_level": 0,
    "donated": 0.0,
    "hashrate": {
        "total": [
            14.97,
            14.93,
            15.46,
            15.42,
            15.47,
            15.39
        ]
    },
    "miners": {
        "now": 19,
        "max": 21
    },
    "upstreams": 19,
    "results": {
        "accepted": 106366,
        "rejected": 1,
        "invalid": 104,
        "expired": 328,
        "avg_time": 1,
        "latency": 1,
        "hashes_total": 2615281856,
        "hashes_donate": 0,
        "best": [
            9774199197,
            2547425724,
            1020369876,
            933069726,
            628625185,
            351285571,
            301182561,
            231818270,
            225349366,
            219780630
        ]
    }
}`

GET /workers.json endpoint

`{
    "hashrate": {
        "total": [
            23.39,
            15.88,
            14.72,
            15.3,
            15.37,
            15.37
        ]
    },
    "workers": [
        [
            "node25",
            "127.0.0.1",
            14,
            95220,
            0,
            5,
            2441780034,
            1526251532766,
            19.26,
            12.5,
            11.4,
            11.72,
            11.76
        ],
        [
            "node26",
            "127.0.0.1",
            2,
            13529,
            0,
            1,
            263142961,
            1526251526696,
            0.55,
            0.92,
            1.15,
            1.27,
            1.27
        ],
        [
            "node27",
            "198.62.109.190",
            2,
            13495,
            0,
            91,
            211034767,
            1526251513109,
            0.89,
            1.32,
            1.0,
            0.99,
            1.01
        ],
        [
            "node28",
            "127.0.0.1",
            1,
            6645,
            1,
            7,
            256587285,
            1526251509612,
            2.67,
            1.13,
            1.16,
            1.3,
            1.32
        ],
        [
            "MineRig2",
            "198.62.109.190",
            0,
            3,
            0,
            0,
            30000,
            1526063537098,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
        ]
    ]
}`


I run 19 miners now, you can get the count from the first JSON on the top, however since i didn't configure all the miners properly with different unique names only several unique ones get displayed in the second JSON, but it should be equal to the number of connected miners just FYI
Let me know if i can be of any other help

**Comment by rodneymo** [comment]
Miner monitor and template dashboards added to 2.1.d.4 (development version).
Will be included in final 2.1 release

**Comment by syncro2017** [comment]
Looks like there are couple of issues, on with the supportxmr pool i think and nother one with parsing data from xmrig-proxy, i posted the traces on bitcointalk thread
